sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true client-test npm test

after_success:
  - docker build -t felipeemerson/multi-client ./client
  - docker build -t felipeemerson/multi-worker ./worker
  - docker build -t felipeemerson/multi-server ./server
  - docker build -t felipeemerson/multi-nginx ./nginx
  - echo "$DOCKER_HUB_PASSWORD" | docker login --username "$DOCKER_HUB_USER" --password-stdin
  - docker push felipeemerson/multi-client
  - docker push felipeemerson/multi-worker
  - docker push felipeemerson/multi-server
  - docker push felipeemerson/multi-nginx

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "Multi-docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-654654591420"
  bucket_path: "multi-docker"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: main