sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t client-test-img -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true client-test-img npm test

after_success:
  - docker build -t felipeemerson/client-img ./client
  - docker build -t felipeemerson/worker-img ./worker
  - docker build -t felipeemerson/server-img ./server
  - docker build -t felipeemerson/nginx-img ./nginx